### PR TITLE
feat: Add database (sqlite) persistence (DEV-3735)

### PR DESCRIPTION
**Pull request by seakayone**
- **Add [Flyway](https://flywaydb.org/) for Database migrations**
- **Use [Sqlite](https://sqlite.org/) as database // add to docker-compose**
- **Use [Quill](https://zio.dev/zio-quill/writing-queries) for queries**
- **Add `Project` entity and persist it in Postgres**
- **Introduces`HealthIndicator` for database, e.g. `/health` endpoint is DOWN if the database is down**
- **Add a just recipe to delete the database** 

Depends on following PR being merged first:
https://github.com/dasch-swiss/ops-deploy/pull/767

### CODE REVIEW

**Comment by siers** [comment]
Is most of the MR similar to the way it was when you made it for postgres?

**Comment by seakayone** [comment]
> Is most of the MR similar to the way it was when you made it for postgres?

Yes, I should have probably just changed that.

The only change in _production code_ is that we now use `Quill.Sqlite` instead of `Quill.Postgres`. The dependencies changed of course.

There is also a slight change in the _test setup_:
One benefit of using sqlite is that in the tests we can directly use sqlite and do not have to maintain an in-memory mock or handle some testcontainers.

**Comment by siers** [comment]
> Yes, I should have probably just changed that PR.
Would've been nice.

> Do not have to maintain an in-memory mock or handle some testcontainers.
Nice.

**Review by siers — APPROVED** [review]

**Review by BalduinLandolt — APPROVED** [review]
thanks! 👍

**Review by mpro7 — APPROVED** [review]
I have only one minor suggestion:

**Pull request merged**
